/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.time.LocalDate;
import static java.time.temporal.ChronoUnit.DAYS;



/**
 *
 * @author tahar
 */
public class accueil extends javax.swing.JFrame {

    /**
     * Creates new form accueil
     */
    public accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seinscrire = new keeptoo.KButton();
        bChercherItineraire = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        bVilleDes = new javax.swing.JTextField();
        dateDebut = new com.github.lgooddatepicker.components.DatePicker();
        dateFin = new com.github.lgooddatepicker.components.DatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seConnecter1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        seinscrire.setForeground(new java.awt.Color(5, 56, 107));
        seinscrire.setText("Inscription");
        seinscrire.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        seinscrire.setkBorderRadius(40);
        seinscrire.setkEndColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkForeGround(new java.awt.Color(5, 56, 107));
        seinscrire.setkHoverColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkHoverEndColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkHoverForeGround(new java.awt.Color(5, 56, 107));
        seinscrire.setkHoverStartColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkSelectedColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkStartColor(new java.awt.Color(92, 219, 149));
        seinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seinscrireActionPerformed(evt);
            }
        });

        bChercherItineraire.setText("Chercher");
        bChercherItineraire.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        bChercherItineraire.setForeground(new java.awt.Color(5, 56, 107));
        bChercherItineraire.setkBorderRadius(40);
        bChercherItineraire.setkEndColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.setkForeGround(new java.awt.Color(5, 56, 107));
        bChercherItineraire.setkHoverColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.setkHoverEndColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.setkHoverForeGround(new java.awt.Color(5, 56, 107));
        bChercherItineraire.setkHoverStartColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.setkSelectedColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.setkStartColor(new java.awt.Color(92, 219, 149));
        bChercherItineraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChercherItineraireActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footer_java.jpg"))); // NOI18N

        bVilleDes.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        bVilleDes.setForeground(new java.awt.Color(5, 56, 107));
        bVilleDes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(92, 219, 149)));
        bVilleDes.setSelectionColor(new java.awt.Color(92, 219, 149));
        bVilleDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVilleDesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 56, 107));
        jLabel2.setText("Date Debut");

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 56, 107));
        jLabel3.setText("Date Fin");

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 56, 107));
        jLabel4.setText("Entrez la ville de destination");

        seConnecter1.setForeground(new java.awt.Color(5, 56, 107));
        seConnecter1.setText("Connexion");
        seConnecter1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        seConnecter1.setkBorderRadius(40);
        seConnecter1.setkEndColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkForeGround(new java.awt.Color(5, 56, 107));
        seConnecter1.setkHoverColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkHoverEndColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkHoverForeGround(new java.awt.Color(5, 56, 107));
        seConnecter1.setkHoverStartColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkSelectedColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkStartColor(new java.awt.Color(92, 219, 149));
        seConnecter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seConnecter1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(seinscrire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(seConnecter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bVilleDes, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(bChercherItineraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(194, 194, 194))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seinscrire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seConnecter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bVilleDes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bChercherItineraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVilleDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVilleDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVilleDesActionPerformed

    private void seinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seinscrireActionPerformed
        new inscription().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seinscrireActionPerformed

    private void seConnecter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seConnecter1ActionPerformed
       new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seConnecter1ActionPerformed

    private void bChercherItineraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChercherItineraireActionPerformed
       int NBRE_JOURS = (int) DAYS.between(dateFin.getDate(),dateDebut.getDate());
       NBRE_JOURS = Math.abs(NBRE_JOURS);
       new list_itineraires(NBRE_JOURS).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bChercherItineraireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton bChercherItineraire;
    private javax.swing.JTextField bVilleDes;
    private com.github.lgooddatepicker.components.DatePicker dateDebut;
    private com.github.lgooddatepicker.components.DatePicker dateFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KButton seConnecter1;
    private keeptoo.KButton seinscrire;
    // End of variables declaration//GEN-END:variables
}
