/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlleurs.ItineraireControlleur;
import java.util.LinkedList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import metier.Itinerary;

/**
 *
 * @author tahar
 */
public class list_itineraires extends javax.swing.JFrame {

    /**
     * Creates new form list_itineraires
     */
          
   private  ItineraireControlleur itc = null;
   private     LinkedList<Itinerary> itinerairesGeneres = null;
   private static int NBRE_JOURS;
    public list_itineraires(int nbre_jours) {
        this.NBRE_JOURS = nbre_jours;
        System.out.println(NBRE_JOURS);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTableUI1 = new mdlaf.components.table.MaterialTableUI();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seConnecter1 = new keeptoo.KButton();
        seinscrire = new keeptoo.KButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItineraires = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voirDetails = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footer_java.jpg"))); // NOI18N

        seConnecter1.setText("Connexion");
        seConnecter1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        seConnecter1.setForeground(new java.awt.Color(5, 56, 107));
        seConnecter1.setkBorderRadius(40);
        seConnecter1.setkEndColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkForeGround(new java.awt.Color(5, 56, 107));
        seConnecter1.setkHoverColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkHoverEndColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkHoverForeGround(new java.awt.Color(5, 56, 107));
        seConnecter1.setkHoverStartColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkSelectedColor(new java.awt.Color(92, 219, 149));
        seConnecter1.setkStartColor(new java.awt.Color(92, 219, 149));
        seConnecter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seConnecter1ActionPerformed(evt);
            }
        });

        seinscrire.setText("Inscription");
        seinscrire.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        seinscrire.setForeground(new java.awt.Color(5, 56, 107));
        seinscrire.setkBorderRadius(40);
        seinscrire.setkEndColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkForeGround(new java.awt.Color(5, 56, 107));
        seinscrire.setkHoverColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkHoverEndColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkHoverForeGround(new java.awt.Color(5, 56, 107));
        seinscrire.setkHoverStartColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkSelectedColor(new java.awt.Color(92, 219, 149));
        seinscrire.setkStartColor(new java.awt.Color(92, 219, 149));
        seinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seinscrireActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox1.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox2.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox2.setText("jCheckBox1");

        jCheckBox3.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox3.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox3.setText("jCheckBox1");

        jCheckBox4.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox4.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox4.setText("jCheckBox1");

        jCheckBox5.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox5.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox5.setText("jCheckBox1");

        jCheckBox6.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox6.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox6.setText("jCheckBox1");

        jCheckBox7.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox7.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox7.setText("jCheckBox1");

        jCheckBox8.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox8.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox8.setText("jCheckBox1");

        jCheckBox9.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox9.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox9.setText("jCheckBox1");

        jCheckBox10.setBackground(new java.awt.Color(92, 219, 149));
        jCheckBox10.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(5, 56, 107));
        jCheckBox10.setText("jCheckBox1");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jCheckBox4))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox3))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox6))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox8))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox10)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(67, 67, 67)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(42, 42, 42)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addGap(45, 45, 45)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox8))
                .addGap(46, 46, 46)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTableItineraires.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTableItineraires.setForeground(new java.awt.Color(5, 56, 107));
        jTableItineraires.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jour", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableItineraires.setGridColor(new java.awt.Color(5, 56, 107));
        jTableItineraires.setSelectionBackground(new java.awt.Color(92, 219, 149));
        jTableItineraires.setSelectionForeground(new java.awt.Color(5, 56, 107));
        jScrollPane1.setViewportView(jTableItineraires);

        jPanel2.setBackground(new java.awt.Color(142, 228, 175));

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 56, 107));
        jLabel2.setText("Vos Itinéraires");

        voirDetails.setForeground(new java.awt.Color(5, 56, 107));
        voirDetails.setText("Voir Details D'un Itinéraire");
        voirDetails.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        voirDetails.setkBorderRadius(40);
        voirDetails.setkEndColor(new java.awt.Color(5, 56, 107));
        voirDetails.setkForeGround(new java.awt.Color(92, 216, 107));
        voirDetails.setkHoverColor(new java.awt.Color(5, 56, 107));
        voirDetails.setkHoverEndColor(new java.awt.Color(5, 56, 107));
        voirDetails.setkHoverForeGround(new java.awt.Color(92, 216, 107));
        voirDetails.setkHoverStartColor(new java.awt.Color(5, 56, 107));
        voirDetails.setkSelectedColor(new java.awt.Color(5, 56, 107));
        voirDetails.setkStartColor(new java.awt.Color(5, 56, 107));
        voirDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voirDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voirDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seinscrire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seConnecter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seConnecter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seinscrire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seConnecter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seConnecter1ActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seConnecter1ActionPerformed

    private void seinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seinscrireActionPerformed
        new inscription().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seinscrireActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
     itc = new  ItineraireControlleur();
     itinerairesGeneres = itc.getItineraires(NBRE_JOURS);  
        afficherDansTableau();
    }//GEN-LAST:event_formWindowOpened

    private void voirDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirDetailsActionPerformed
        int index = jTableItineraires.getSelectedRow();
        if(index == -1)
            showMessageDialog(null,"Veuillez séléctionnez une ligne du tableau ci-dessous");
        else{
            new itineraire_detaille(itinerairesGeneres.get(index),NBRE_JOURS).setVisible(true);
           this.dispose();
            
        }
    }//GEN-LAST:event_voirDetailsActionPerformed

       private void afficherDansTableau() {
       jTableItineraires.clearSelection();
        String[] cnames = {"Jour",
            "Nombre"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(cnames);
         jTableItineraires.setModel(model);
   
        for (Itinerary  itinerary : itinerairesGeneres){
           Object[] rowData =  new Object[2];
            rowData[0] = itinerary.getId();
            rowData[1] = itinerary.getLocaux().size();
            model.addRow(rowData);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_itineraires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_itineraires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_itineraires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_itineraires.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_itineraires(NBRE_JOURS).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableItineraires;
    private keeptoo.KGradientPanel kGradientPanel1;
    private mdlaf.components.table.MaterialTableUI materialTableUI1;
    private keeptoo.KButton seConnecter1;
    private keeptoo.KButton seinscrire;
    private keeptoo.KButton voirDetails;
    // End of variables declaration//GEN-END:variables
}
